apiVersion: v1
kind: Service
metadata:
  name: hello-boathouse-service
spec:
  type: NodePort
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
      nodePort: 30068
  selector:
    app: hello-boathouse