apiVersion: v1
kind: Service
metadata:
  name: hello-boathouse-service
spec:
  type: NodePort
  ports:
    - name: "3001"
      port: 3001
      targetPort: 3001
      nodePort: 30068
  selector:
    app: hello-boathouse
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-boathouse-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello-boathouse
  template:
    metadata:
      labels:
        app: hello-boathouse
    spec:
      containers:
      - name: hello-boathouse
        image: registry.cn-hangzhou.aliyuncs.com/boathouse216/hello-boathouse:v2
        ports:
        - name: nodejs-port
          containerPort: 3001