on:
  push:
    branches: [ main ]

jobs:
  Sync-To-Gitee:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
        # 来源仓库
        source-repo: "git@github.com:idcf-boat-house/boathouse-labs.git"
        # 目标仓库
        destination-repo: "git@gitee.com:idcf-boat-house/boathouse-labs.git"
